[WinEventLog://Application]
index = endpoint
disabled = 0

[WinEventLog://Security]
index = endpoint
disabled = 0
[WinEventLog://System]

index = endpoint
disabled = 0

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = endpoint
disabled = 0
renderXml = true
source = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
